{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "scraper progetto.ipynb",
      "provenance": [],
      "collapsed_sections": [],
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/LgLuigigallo/Webscraper/blob/main/app.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "o1BmckKZonBb",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "c1b5ebca-a706-4172-e296-f158a6042b05"
      },
      "source": [
        "!pip install beautifulsoup4\n",
        "!pip install requests\n",
        "!pip install lxml\n",
        "import requests"
      ],
      "execution_count": 1,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.7/dist-packages (4.6.3)\n",
            "Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (2.23.0)\n",
            "Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests) (1.24.3)\n",
            "Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests) (2.10)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests) (2021.5.30)\n",
            "Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests) (3.0.4)\n",
            "Requirement already satisfied: lxml in /usr/local/lib/python3.7/dist-packages (4.2.6)\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "bCe4ZqxHiKs2",
        "outputId": "12e402f0-5cc7-4432-ec42-04b03f490c09"
      },
      "source": [
        "!pip install Flask\n",
        "!pip install flask-restful\n",
        "!pip install flask-ngrok\n",
        "!pip install gunicorn\n",
        "from flask import Flask, jsonify, render_template\n",
        "from flask_restful import Resource, Api\n",
        "from flask_ngrok import run_with_ngrok"
      ],
      "execution_count": 2,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Requirement already satisfied: Flask in /usr/local/lib/python3.7/dist-packages (1.1.4)\n",
            "Requirement already satisfied: Jinja2<3.0,>=2.10.1 in /usr/local/lib/python3.7/dist-packages (from Flask) (2.11.3)\n",
            "Requirement already satisfied: click<8.0,>=5.1 in /usr/local/lib/python3.7/dist-packages (from Flask) (7.1.2)\n",
            "Requirement already satisfied: Werkzeug<2.0,>=0.15 in /usr/local/lib/python3.7/dist-packages (from Flask) (1.0.1)\n",
            "Requirement already satisfied: itsdangerous<2.0,>=0.24 in /usr/local/lib/python3.7/dist-packages (from Flask) (1.1.0)\n",
            "Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from Jinja2<3.0,>=2.10.1->Flask) (2.0.1)\n",
            "Collecting flask-restful\n",
            "  Downloading Flask_RESTful-0.3.9-py2.py3-none-any.whl (25 kB)\n",
            "Requirement already satisfied: pytz in /usr/local/lib/python3.7/dist-packages (from flask-restful) (2018.9)\n",
            "Requirement already satisfied: Flask>=0.8 in /usr/local/lib/python3.7/dist-packages (from flask-restful) (1.1.4)\n",
            "Collecting aniso8601>=0.82\n",
            "  Downloading aniso8601-9.0.1-py2.py3-none-any.whl (52 kB)\n",
            "\u001b[K     |████████████████████████████████| 52 kB 1.0 MB/s \n",
            "\u001b[?25hRequirement already satisfied: six>=1.3.0 in /usr/local/lib/python3.7/dist-packages (from flask-restful) (1.15.0)\n",
            "Requirement already satisfied: Werkzeug<2.0,>=0.15 in /usr/local/lib/python3.7/dist-packages (from Flask>=0.8->flask-restful) (1.0.1)\n",
            "Requirement already satisfied: click<8.0,>=5.1 in /usr/local/lib/python3.7/dist-packages (from Flask>=0.8->flask-restful) (7.1.2)\n",
            "Requirement already satisfied: Jinja2<3.0,>=2.10.1 in /usr/local/lib/python3.7/dist-packages (from Flask>=0.8->flask-restful) (2.11.3)\n",
            "Requirement already satisfied: itsdangerous<2.0,>=0.24 in /usr/local/lib/python3.7/dist-packages (from Flask>=0.8->flask-restful) (1.1.0)\n",
            "Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from Jinja2<3.0,>=2.10.1->Flask>=0.8->flask-restful) (2.0.1)\n",
            "Installing collected packages: aniso8601, flask-restful\n",
            "Successfully installed aniso8601-9.0.1 flask-restful-0.3.9\n",
            "Collecting flask-ngrok\n",
            "  Downloading flask_ngrok-0.0.25-py3-none-any.whl (3.1 kB)\n",
            "Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from flask-ngrok) (2.23.0)\n",
            "Requirement already satisfied: Flask>=0.8 in /usr/local/lib/python3.7/dist-packages (from flask-ngrok) (1.1.4)\n",
            "Requirement already satisfied: click<8.0,>=5.1 in /usr/local/lib/python3.7/dist-packages (from Flask>=0.8->flask-ngrok) (7.1.2)\n",
            "Requirement already satisfied: Jinja2<3.0,>=2.10.1 in /usr/local/lib/python3.7/dist-packages (from Flask>=0.8->flask-ngrok) (2.11.3)\n",
            "Requirement already satisfied: itsdangerous<2.0,>=0.24 in /usr/local/lib/python3.7/dist-packages (from Flask>=0.8->flask-ngrok) (1.1.0)\n",
            "Requirement already satisfied: Werkzeug<2.0,>=0.15 in /usr/local/lib/python3.7/dist-packages (from Flask>=0.8->flask-ngrok) (1.0.1)\n",
            "Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python3.7/dist-packages (from Jinja2<3.0,>=2.10.1->Flask>=0.8->flask-ngrok) (2.0.1)\n",
            "Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->flask-ngrok) (2.10)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->flask-ngrok) (2021.5.30)\n",
            "Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->flask-ngrok) (3.0.4)\n",
            "Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->flask-ngrok) (1.24.3)\n",
            "Installing collected packages: flask-ngrok\n",
            "Successfully installed flask-ngrok-0.0.25\n",
            "Collecting gunicorn\n",
            "  Downloading gunicorn-20.1.0-py3-none-any.whl (79 kB)\n",
            "\u001b[K     |████████████████████████████████| 79 kB 3.2 MB/s \n",
            "\u001b[?25hRequirement already satisfied: setuptools>=3.0 in /usr/local/lib/python3.7/dist-packages (from gunicorn) (57.4.0)\n",
            "Installing collected packages: gunicorn\n",
            "Successfully installed gunicorn-20.1.0\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "BZeE0MEg7hxV",
        "outputId": "89d1430e-d745-462e-c10a-5d2c6aded6a1"
      },
      "source": [
        "from google.colab import drive\n",
        "drive.mount('/content/drive')"
      ],
      "execution_count": 10,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Mounted at /content/drive\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "9niOGISWpnyl"
      },
      "source": [
        "# #geographical search\n",
        "regione=\"Lazio\"\n",
        "provincia= \"Viterbo\"\n",
        "professione= \"idraulico\""
      ],
      "execution_count": 3,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "IePcw_-7pHSt",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 35
        },
        "outputId": "77d9606e-3aec-4902-957d-d8d2cfcfe35e"
      },
      "source": [
        "#building link\n",
        "from bs4 import BeautifulSoup as bs\n",
        "link= \"https://www.paginegialle.it/ricerca/\" + professione + \"/\" + provincia + \"p-1?mr=200&rk=1\"\n",
        "r = requests.get(\"https://www.paginegialle.it/ricerca/\" + professione + \"/\" + provincia + \"p-2?mr=200&rk=1\")\n",
        "content = r.text\n",
        "soup = bs(content, \"lxml\")\n",
        "link"
      ],
      "execution_count": 4,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "application/vnd.google.colaboratory.intrinsic+json": {
              "type": "string"
            },
            "text/plain": [
              "'https://www.paginegialle.it/ricerca/idraulico/Viterbop-1?mr=200&rk=1'"
            ]
          },
          "metadata": {},
          "execution_count": 4
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "SBov3CUYwAjg",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "5e0b4af3-5577-4c67-b08a-d964724df6dc"
      },
      "source": [
        "#number of results\n",
        "results=soup.find(\"span\", class_=\"results-info__numresults\")\n",
        "res = results.text.splitlines()\n",
        "n_results = int(res[1].lstrip().rstrip())\n",
        "n_results"
      ],
      "execution_count": 5,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "70"
            ]
          },
          "metadata": {},
          "execution_count": 5
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "4mhiXFso4Zla",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "13747d82-44f7-48c8-f89c-5a2aeccb4a3d"
      },
      "source": [
        "#contatore risultati\n",
        "import pandas as pd\n",
        "import numpy as np\n",
        "counter_res=0\n",
        "import json\n",
        "from datetime import date\n",
        "dat=pd.DataFrame(columns=['Name', 'Cathegory', 'Phone','Address'])\n",
        "# ciclo inizializzato per un massimo di 6 pagine con 80 risultati l-una\n",
        "try:\n",
        "\n",
        "  for page in range(0,6):\n",
        "      page=page+1\n",
        "      # link generation\n",
        "      link= \"https://www.paginegialle.it/ricerca/\" + professione + \"/\" + provincia + \"/p-\"+str(page)+\"?mr=80&rk=1\"\n",
        "      # print(link)\n",
        "      r = requests.get(\"https://www.paginegialle.it/ricerca/\" + professione + \"/\" + provincia + \"/p-\"+str(page)+\"?mr=80&rk=1\")\n",
        "      print(link)\n",
        "      content = r.text\n",
        "      soup = bs(content, \"lxml\")\n",
        "      # soup extraction\n",
        "      name = soup.find_all(\"h2\", {\"class\":\"list-element__title text-medium \", \"itemprop\":\"name\"})\n",
        "      addr_street = soup.find_all(\"span\", {\"itemprop\":\"streetAddress\"})\n",
        "      addr_loc = soup.find_all(\"span\", {\"itemprop\":\"addressLocality\"})\n",
        "      addr_sugg= soup.find_all(\"span\",  { \"itemprop\":\"address\"})\n",
        "      phone_sugg=soup.find_all(\"div\", {\"class\":\"btn__label\"}) \n",
        "      phone = soup.find_all(\"div\", {\"class\":\"btn__label\", \"itemprop\":\"telephone\"})\n",
        "      categ = soup.find_all(\"div\",{\"class\":\"list-element__category text-medium color-gray-4 mb-10\"})\n",
        "      # result extraction\n",
        "\n",
        "      for i in range(0,len(name)-1):\n",
        "          \n",
        "          counter_res+=1\n",
        "         \n",
        "          # deleting suggested result (paid)\n",
        "          if  (name[i].find(\"a\")) == (name[i].find(\"a\", {\"data-pag\":\"Grande Cliente/RGS\"})) :\n",
        "              print('*****************************************Name suggested removed************************************ \\n' )\n",
        "              phone.insert(i,'000' )\n",
        "              name.remove(name[i])\n",
        "\n",
        "          if (name[i].find(\"a\")) != (name[i].find(\"a\", {\"data-pag\":\"Grande Cliente/RGS\"})) :\n",
        "            # print(i)  \n",
        "            try: \n",
        "              print(name[i].find(\"a\").text)\n",
        "            except:\n",
        "              name[i]='NaN'\n",
        "              print(\"No name\")\n",
        "            try:\n",
        "              print(categ[i].text.rstrip().lstrip())\n",
        "            except:\n",
        "              categ[i]='NaN'\n",
        "              print(\"No categories\")\n",
        "            try:\n",
        "              print(phone[i].text)\n",
        "            except:\n",
        "              phone[i]='NaN'\n",
        "              print(\"No number\")\n",
        "            try: \n",
        "                  print((addr_street[i].text) + ' '+ (addr_loc[i].text)+\"\\n\")        \n",
        "            except: \n",
        "                  addr_street[i]='NaN'\n",
        "                  addr_loc[i]='Nan'\n",
        "                  print('No address info')\n",
        "          try:  \n",
        "            dat = dat.append([{'Name':name[i].find(\"a\").text, 'Cathegory':categ[i].text.rstrip().lstrip(),'Phone':phone[i].text,\n",
        "                             'Address':((addr_street[i].text) + ' '+ (addr_loc[i].text))  }], ignore_index=True)\n",
        "          except Exception as e:\n",
        "            print(e)\n",
        "      \n",
        "except Exception as e: \n",
        "  print(e)\n",
        "            \n",
        "  print(\"\\n Errore,\",\"Risultati trovati\", counter_res,\"totale risultati\",n_results,sep=' ')\n",
        "\n",
        "\n",
        "with open('dat.json', 'w') as f:\n",
        "  f.write(dat.to_json())\n",
        "\n",
        "\n",
        "print(\"\\n Risultati\", counter_res,\"totale risultati\",n_results, \"Risultati omessi\",n_results-counter_res ,sep=' ')"
      ],
      "execution_count": 6,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "https://www.paginegialle.it/ricerca/idraulico/Viterbo/p-1?mr=80&rk=1\n",
            "Termoidraulica Burioni\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "0761 345283\n",
            "Viale Bruno Buozzi, 19 Viterbo\n",
            "\n",
            "Alma Srls\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "349 0620332\n",
            "15/D, Viale Baracca Francesco Viterbo\n",
            "\n",
            "Termoidraulica di Federico Rossi\n",
            "IMPRESE EDILI\n",
            "0761 325909\n",
            "19, Via S. Pietro Viterbo\n",
            "\n",
            "Ce.Mar Snc di Cevolo Gianluca e Marcomigni Roberto\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "328 5387037\n",
            "Via Galileo Galilei, 1 Viterbo\n",
            "\n",
            "Fratelli Sorrentino\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "0761 220625\n",
            "39/B, Via Belluno Viterbo\n",
            "\n",
            "La Idrotermica S.r.l.\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "328 8730294\n",
            "1, Via Di Pianoscarano Viterbo\n",
            "\n",
            "Termoidraulica di Stella Sergio & C. S.n.c.\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "0761 228228\n",
            "50, Viale Buozzi Bruno Viterbo\n",
            "\n",
            "Selvaggini Angelo\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "360 506181\n",
            "Snc, Via Cava Di Gorga Viterbo\n",
            "\n",
            "Group Itec S.r.l.\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "0761 251609\n",
            "20, Strada Riello Viterbo\n",
            "\n",
            "Fabiani Marco\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "328 9195410\n",
            "24, Strada Statale Cassia Sud Viterbo\n",
            "\n",
            "Edg Impianti Tecnologici S.r.l.\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "0761 253607\n",
            "13, Via Latini Latino Viterbo\n",
            "\n",
            "Cencioni Stefano\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "0761 309276\n",
            "44/A, Strada Salamaro Viterbo\n",
            "\n",
            "C.A.I.V.I.T. Consorzio Artigiano fra Installatori Viterbesi Imp Ianti Termoidraulici\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "0761 352884\n",
            "10, Via Mainella Duilio Viterbo\n",
            "\n",
            "Termoidraulica Commerciale Caivit\n",
            "IMPIANTI CONDIZIONAMENTO ARIA - INSTALLAZIONE E MANUTENZIONE\n",
            "0761 251144\n",
            "Via Duilio Mainella, 10 Viterbo\n",
            "\n",
            "Belli Srl\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "0761 354514\n",
            "Via Guidobaldi Ettore Viterbo\n",
            "\n",
            "B.V.S. S.R.L..\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "0761 769987\n",
            "1, Strada Cimina Viterbo\n",
            "\n",
            "Termoidraulica Commerciale Caivit S.r.l\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "0761 352245\n",
            "Via Cassia Nord Viterbo\n",
            "\n",
            "Impianti Termoidraulici De Luca Sandro\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "338 6696273\n",
            "Strada Montarone, 6 Viterbo\n",
            "\n",
            "Termoidraulica Pompei Gianni\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "360 713098\n",
            "17, Via S. Rosella Viterbo\n",
            "\n",
            "Centro Assistenza del Calore\n",
            "IDRAULICI E LATTONIERI\n",
            "0761 340627\n",
            "Viale Fiume, 81/A Viterbo\n",
            "\n",
            "So.Vit. Termoidraulica di Maraghelli Claudio e C. S.a.s.\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "0761 263415\n",
            "Snc, Strada Torre Del Guercio Viterbo\n",
            "\n",
            "Fevis di Vincenzo Femminella\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "0761 288162\n",
            "11/B, Strada Romana Bagnaia\n",
            "\n",
            "Edil Restauri Installazioni Caldaie - Solare Termico - Stufe a Pellet\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "324 8622953\n",
            "9, V. Della Quercia Vitorchiano\n",
            "\n",
            "Sebo Impianti di Sergio Boccialoni\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "0761 747074\n",
            "70, Contrada Fornacchia Soriano Nel Cimino\n",
            "\n",
            "Panfili Marco\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "0761 746194\n",
            "41, Via S. Caterina Soriano Nel Cimino\n",
            "\n",
            "Arriga Sandro\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "0761 745720\n",
            "12, Vicolo Del Pratarello Soriano Nel Cimino\n",
            "\n",
            "Gattei Nicola\n",
            "IDRAULICI E LATTONIERI\n",
            "0761 743104\n",
            "Km. 18.450, Strada Ortana Soriano Nel Cimino\n",
            "\n",
            "S.A.P. di Prosperi E. & C. S.a.s.\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "0761 748856\n",
            "6, Via Delle Mole Soriano Nel Cimino\n",
            "\n",
            "Termoidraulica Fontana Fabrizio\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "0761 750804\n",
            "Snc, Viale Rimembranze Canepina\n",
            "\n",
            "Idroterm di Pollastrello Fausto\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "338 9642420\n",
            "Via Pistoia, 3 Viterbo\n",
            "\n",
            "Di Sante Giacomo\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "360 821024\n",
            "Via Roma, 116/A Vetralla\n",
            "\n",
            "Persi Roberto\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "0761 367203\n",
            "52, Via Delle Grazie Viterbo\n",
            "\n",
            "Pallotta Angelo\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "0761 747001\n",
            "6/B, Via Rigo Viterbo\n",
            "\n",
            "*****************************************Name suggested removed************************************ \n",
            "\n",
            "Termotecnica S.n.c. di Ippoliti Simona & C.\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "No number\n",
            "20, Via Padova Bomarzo\n",
            "\n",
            "'str' object has no attribute 'text'\n",
            "Professional Gas S.n.c. di Moroni F. e Crocicchia A.\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "0761 924070\n",
            "12, Via Minzoni Don Vallerano\n",
            "\n",
            "Burla Renzo\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "0761 754299\n",
            "19, Strada Fastello Viterbo\n",
            "\n",
            "B.P. Srl\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "0761 912166\n",
            "48, Via Cassia Montefiascone\n",
            "\n",
            "Bertoccini Mario\n",
            "IDRAULICI E LATTONIERI\n",
            "0761 820859\n",
            "39/A, Via Verentana Montefiascone\n",
            "\n",
            "G. & G. S.r.l. Semplificata\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "0761 825467\n",
            "18, Via Contadini Giuseppe Montefiascone\n",
            "\n",
            "Falisca Impianti S.n.c. di Cimichella Ennio e Figli\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "0761 959085\n",
            "22, Via Indipendenza Montefiascone\n",
            "\n",
            "Saraca Carlo Termoidraulica\n",
            "RISCALDAMENTO - IMPIANTI E MANUTENZIONE\n",
            "0761 820292\n",
            "38, Via Salotti Cardinale Montefiascone\n",
            "\n",
            "Caciola Francesco\n",
            "IDRAULICI E LATTONIERI\n",
            "335 1509696\n",
            "Snc, Via Roma Celleno\n",
            "\n",
            "Gianlorenzo Cesare\n",
            "IDRAULICI E LATTONIERI\n",
            "335 5390834\n",
            "148, Via Asinello Montefiascone\n",
            "\n",
            "Gianlorenzo Valdo\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "0761 824784\n",
            "148, Via Asinello Montefiascone\n",
            "\n",
            "Termica 2014 di Ciappici Stefano\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "0761 824853\n",
            "7, Strada Provinciale Valleranese Fabrica Di Roma\n",
            "\n",
            "Termoidraulica 2007 di Cola Giampaolo\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "0761 090192\n",
            "2, Via Notazie Montefiascone\n",
            "\n",
            "Guastini Srl\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "328 2586869\n",
            "1, Via Sandro Pertini Ronciglione\n",
            "\n",
            "Nervini Guido\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "0761 625102\n",
            "98, Via S. Giovanni Ronciglione\n",
            "\n",
            "B.S. Impianti S.n.c. di Bronco Silvano e Scarponi Virgilio\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "0761 650184\n",
            "2, Via Giuseppe Mazzini Graffignano\n",
            "\n",
            "https://www.paginegialle.it/ricerca/idraulico/Viterbo/p-2?mr=80&rk=1\n",
            "D.A.L. Termoidraulica S.r.l.\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "338 5713903\n",
            "13, Via Barco Fabrica Di Roma\n",
            "\n",
            "Ricci Costruzioni\n",
            "IMPRESE EDILI\n",
            "339 4381842\n",
            "LocalitÃ  Lungara, 26 Ronciglione\n",
            "\n",
            "A.B.Idrotermica di Baldi Carlo e Andreotti Giuseppe S.n.c.\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "0761 678897\n",
            "25, Viale Matteotti G. Capranica\n",
            "\n",
            "Termoidraulica Fioretto\n",
            "IDRAULICI E LATTONIERI\n",
            "339 1136590\n",
            "Via Campo Sportivo, 9 Fabrica di Roma\n",
            "\n",
            "Tardani Francesco\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "347 4992766\n",
            "5, Via Conventino Graffignano\n",
            "\n",
            "2 Emme Roma di Morini Ivano\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "0761 569471\n",
            "115, Viale Degli Eroi Fabrica Di Roma\n",
            "\n",
            "P.F.C. di Candeori Riccardo\n",
            "IDRAULICI\n",
            "0761 901150\n",
            "15, Piazza Del Comune Graffignano\n",
            "\n",
            "Re Roberto\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "0761 958169\n",
            "Snc, Via S. Paolino Tuscania\n",
            "\n",
            "Etruria Impianti Srl\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "0761 1973008\n",
            "28, Via Varisco Col. Antonio Tuscania\n",
            "\n",
            "A.T Clima Sys Snc di Crocetti e Cascitti\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "346 1786125\n",
            "Via Raniero Bustelli, 15 Tuscania\n",
            "\n",
            "Impianti Termoidraulici di Muzi Alberto\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "0744 904670\n",
            "1/C, Vocabolo Carpineto Alviano\n",
            "\n",
            "Edilizia S. Valentino\n",
            "RISCALDAMENTO - APPARECCHI E MATERIALI\n",
            "0744 904669\n",
            "Via degli Artigiani, 7 Alviano\n",
            "\n",
            "Professional Termica S.n.c. di Ottaviani Daniele e Prosperi Franc\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "0761 573101\n",
            "21/E, Via Marconi Giovanni Corchiano\n",
            "\n",
            "Forniture Srl\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "0761 1935683\n",
            "64, Via San Vincenzo Bassano Romano\n",
            "\n",
            "Idroclima di Boldorini Adriano\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "0761 635111\n",
            "9, Via Del Vignola Bassano Romano\n",
            "\n",
            "Micozzi Amedeo\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "338 3631112\n",
            "6, Strada Bassanese Sutri\n",
            "\n",
            "Ramacciani Roberto\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "0761 793217\n",
            "53, Viale Armando Diaz Bagnoregio\n",
            "\n",
            "Idraulica Gi-Co di Costantini Giuseppe\n",
            "IMPIANTI IDRAULICI E TERMOIDRAULICI\n",
            "348 8801046\n",
            "7, Via Lamarante Soriano Nel Cimino\n",
            "\n",
            "Eurolattoneria S.n.c. dei F.lli Castellani Riccardo e Roberto\n",
            "IDRAULICI E LATTONIERI\n",
            "0761 820978\n",
            "Localita' Le Guardie Montefiascone\n",
            "\n",
            "https://www.paginegialle.it/ricerca/idraulico/Viterbo/p-3?mr=80&rk=1\n",
            "https://www.paginegialle.it/ricerca/idraulico/Viterbo/p-4?mr=80&rk=1\n",
            "https://www.paginegialle.it/ricerca/idraulico/Viterbo/p-5?mr=80&rk=1\n",
            "https://www.paginegialle.it/ricerca/idraulico/Viterbo/p-6?mr=80&rk=1\n",
            "\n",
            " Risultati 68 totale risultati 70 Risultati omessi 2\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "dn4o5Wli2rzt",
        "outputId": "18e1f542-d0ed-4c4d-fb10-7044a79ebadf"
      },
      "source": [
        "from flask import Flask, jsonify,render_template\n",
        "import html\n",
        "app=Flask(__name__,template_folder='/content/drive/MyDrive/templates')\n",
        "run_with_ngrok(app)\n",
        "with open('/content/dat.json', 'r') as myfile:\n",
        "      data = myfile.read()\n",
        "\n",
        "\n",
        "@app.route('/', methods=(\"POST\", \"GET\"))\n",
        "def html_table():\n",
        "\n",
        "    return render_template('simple.html',  tables=[dat.to_html(classes='data')], header=\"true\")\n",
        "\n",
        "app.run()"
      ],
      "execution_count": 14,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            " * Serving Flask app \"__main__\" (lazy loading)\n",
            " * Environment: production\n",
            "\u001b[31m   WARNING: This is a development server. Do not use it in a production deployment.\u001b[0m\n",
            "\u001b[2m   Use a production WSGI server instead.\u001b[0m\n",
            " * Debug mode: off\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            " * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            " * Running on http://296a-35-234-20-219.ngrok.io\n",
            " * Traffic stats available on http://127.0.0.1:4040\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "127.0.0.1 - - [15/Sep/2021 10:13:07] \"\u001b[37mGET / HTTP/1.1\u001b[0m\" 200 -\n",
            "127.0.0.1 - - [15/Sep/2021 10:13:08] \"\u001b[33mGET /favicon.ico HTTP/1.1\u001b[0m\" 404 -\n",
            "127.0.0.1 - - [15/Sep/2021 10:13:10] \"\u001b[37mGET / HTTP/1.1\u001b[0m\" 200 -\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "2A2AUqrM37mp"
      },
      "source": [
        ""
      ],
      "execution_count": 7,
      "outputs": []
    }
  ]
}